repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.12.6
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        args: [ "." ]
        language: system
        pass_filenames: false
